### ISSUE TITLE
Cannot install on mac

### ISSUE THREAD

**Issue by dangarfield** [udarrr/opencv4nodejs-prebuilt-install#3]
Details:
- MacOS - Ventura 13.4.1 (22F82)
- Processor - Apple M2 Max
- Nodejs - v20.3.1
- npm - 9.7.2

Error:
- `npm i opencv4nodejs-prebuilt-install` - Successful install, no issues
- No 'build' folder in `node_modules/opencv4nodejs-prebuilt-install`, only `lib`
- When running a node app, using `const cv = require('opencv4nodejs-prebuilt-install')` -> `cv` is `undefined`

I'm struggling to get opencv4nodejs installed properly, and I see that you've done a great job of prebuilding. Should my system work or is this to be expected at this point?
Thanks

**Comment by udarrr** [comment]
Yes M2 is ARM64 and currently the tool don't support the type of arch. I'm supporting x64 at the moment
Generally it's possible to build necessary prebuilds but unfortunately i don't have available instance for that.

**Comment by deewata36** [comment]
> When running a node app, using const cv = require('opencv4nodejs-prebuilt-install') -> cv is undefined

Also getting the same issue as above with Linux. I do have the `build` and `lib` folders. No issues installing and using it on my Windows pc. Would appreciate any help @udarrr 

Contents of build/Release/:
![image](https://github.com/udarrr/opencv4nodejs-prebuilt-install/assets/165397836/71d5c89a-91d8-42dd-8fa6-6fbf11b6cdff)

Content of lib:
![image](https://github.com/udarrr/opencv4nodejs-prebuilt-install/assets/165397836/0a6188a0-4ef4-46bd-8ae6-807ccadef65f)

**Comment by deewata36** [comment]
Not sure what was wrong, but installing someone's fork of this library solved the issue

**Comment by ohnosharks** [comment]
@deewata36 So uhh what was the fork?

**Comment by udarrr** [comment]
resolved in 4.1.209
